version: "3.8"

services:
  app:
    image: natinael/aqlesia-frontend:v1
    container_name: kesis-appointment-app
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000/v1
